# Database settings.
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.cj.jdbc.Driver
  # the username
  user: root
  # the password
  password: Srishti@123
  # the JDBC URL; the database is called hello_world
  url: jdbc:mysql://localhost:3306/todoapp
  # the SQL query to run when validating a connection's liveness
  #validationQuery: "SELECT 1"
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
